steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/project-1b9e70ea-a8fc-4cf6-b12/cloud-run-source-deploy/dsacontents-ai-api:$COMMIT_SHA'
      - '-f'
      - 'ai-server/Dockerfile'
      - 'ai-server'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'asia-northeast3-docker.pkg.dev/project-1b9e70ea-a8fc-4cf6-b12/cloud-run-source-deploy/dsacontents-ai-api:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - dsacontents-ai-api
      - '--image=asia-northeast3-docker.pkg.dev/project-1b9e70ea-a8fc-4cf6-b12/cloud-run-source-deploy/dsacontents-ai-api:$COMMIT_SHA'
      - '--region=asia-northeast3'
      - '--platform=managed'
      - '--quiet'

images:
  - 'asia-northeast3-docker.pkg.dev/project-1b9e70ea-a8fc-4cf6-b12/cloud-run-source-deploy/dsacontents-ai-api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
